### PR TITLE
Update index.mdx

### PR DESCRIPTION
**Pull request by jackyng88**
Initial update of Environment pre-reqs

### CODE REVIEW

**Review by jesusmah — COMMENTED** [review]
@jackyng88 thanks for taking care of the python section. It overall looks good but let me suggest one enhancement that may help people reuse the python consumer and producer more easily.

The pieces that I am missing in the consumer/producer are:
1. How to call them to actually produce and consume a message.
2. How do I provide the configuration consumer and producer need to operate (scram username and password, topic name, message, pem certificate...

I'd reuse the scripts we have in https://github.com/ibm-cloud-architecture/refarch-eda-tools/tree/master/Avro/src/Confluent/Plain as these have a very neat and clean way of declaring the needed arguments and reading these. You would need to declare arguments for scram username and password and pem certificate rather than reading those from env variables and modify consumer and producer accordingly (you would need to pass the scram username and password and the pem certificate to the constructor) or you could use env variables for all if that is easier for you (which would require modifications in the constructor as well) and provide instructions for setting those env variables before calling the producer and consumer.

I am fine either way as long as we add these missing pieces to understand how to call the producer and consumer and how and what credentials and certificates need to be provided.

**Comment by jbcodeforce** [comment]
Please also add references to openshift installation, cp4i installation, and then as we may move out of appsody we can use a new repo: refarch-eda-quick-starts with subfolder with a quarkus producer , a quarkus consumer, a kafka streams, a node project, a python project,... references also our docs about getting knowledge, there is one updated by rick recently.

**Comment by jackyng88** [comment]
I posted an updated with code inline for Quarkus and Python. I will eventually get around to working on posting a Node sample app.

**Comment by jesusmah** [comment]
@jackyng88 The Voyage microservice in our reference application is implemented using node if you want to have a look at it: https://github.com/ibm-cloud-architecture/refarch-kc-ms/tree/master/voyages-ms

More precisely, you can find the kafka code and its configuration in /server/utils. Then, we consume and produce messages in /server/routers/voyage.js. Line 199 on that file is the entry point by defining a topic and a callback function to execute on each message received. In it, you can see how we emit events to kafka as well.

**Comment by jackyng88** [comment]
So I managed to get a simple Node.js producer application to send messages to ESV10 so the code is in the markdown, the consumer doesn't work as of yet so I haven't put it down yet.

**Pull request merged**
